from typing import Protocol
from ..model import Embedding, DocumentId

Score = float

class Document:
    id: DocumentId
    text: str

class LLM(Protocol):
    async def embed_query(self, query: str) -> Embedding: ...
    async def embed_documents(self, documents: list[Document]) -> list[Embedding]: ...

class DocumentDatabase(Protocol):
    async def put(self, documents: list[Document]) -> None: ...
    async def search(self, query: str) -> list[tuple[Document, Score]]: ...

class Database(Protocol):
    async def create() -> None: ...
    async def read() -> None: ...
    async def update() -> None: ...
    async def delete() -> None: ...